### ISSUE TITLE
Use the backend to differentiate staff and student users

### ISSUE THREAD

**Issue by wltan** [Source-Academy-Game/cadet-frontend#3]
Staff roles focus more on the development and authoring of the game system, whereas students only need to concern themselves with the gameplay experience.
It is hence necessary to tell the two user groups apart to facilitate further development.

**Comment by Cheng20010201** [comment]
Currently the backend system has 3 roles implemented already: staff, student, admin. The current system is already able to differentiate the staff and student users.
