### ISSUE TITLE
Save the student's game state on the backend rather than locally

### ISSUE THREAD

**Issue by wltan** [Source-Academy-Game/cadet-frontend#6]
Currently, all of the student's game completion progress (e.g. completed quests, obtained collectibles) is stored locally. This means that the game state for the student is not transferable between devices, and will reset if the student (for instance) switches browsers or clears their browsing data.

Future features such as achievements must remain consistent for the student, which is currently impossible due to the limitation described above.

**Comment by wltan** [comment]
Note: Need to figure out exactly what game state elements need to be stored, and where in the engine to save/load them.

**Comment by Cheng20010201** [comment]
What should collectibles be, and how can collectibles be obtained (from game, or from missions?)

**Comment by wltan** [comment]
Collectibles are triggered by certain in-game objects. Example:
```
<TEMP_OBJECT id="lk-robotDog" name="lk-robotDog" skin="normal" x="1539" y="472">
  <SEQUENCE>
    <POPUP>
      <IMAGE>robotDog.png</IMAGE>
      <NARRATION>The robot dog emits a sharp, mechanical bark and follows you around with its tail wagging.</NARRATION>
      <DIALOGUE>
        <SPEECH speaker="lok-kim" expression="happy">(redacted speech)</SPEECH>
      </DIALOGUE>
    </POPUP>
  </SEQUENCE>
  <EXTERNAL_ACTION name="pickUpCollectible">
    <ARGUMENT>lk-robotDog</ARGUMENT>
  </EXTERNAL_ACTION>
</TEMP_OBJECT>
```
It should be possible to manipulate the state of collectibles with the appropriate API.
https://github.com/Source-Academy-Game/cadet-frontend/blob/a3e14d95db38988fcb45ae3f167bcc861e7bf786/src/components/academy/game/create-initializer.js#L39
https://github.com/Source-Academy-Game/cadet-frontend/blob/a3e14d95db38988fcb45ae3f167bcc861e7bf786/src/components/academy/game/backend/game-state.js#L44-L49

Right now the data isn't used for anything other than controlling where to display the collected objects.
https://github.com/Source-Academy-Game/cadet-frontend/blob/a3e14d95db38988fcb45ae3f167bcc861e7bf786/src/components/academy/game/object-manager/object-manager.js#L161-L170

**Comment by athuyaoo** [comment]
This should work if it merges. @wltan
