### ISSUE TITLE
Implement a system to manage which stories are active at any given point in time

### ISSUE THREAD

**Issue by wltan** [Source-Academy-Game/cadet-frontend#7]
Currently, at any given point in time all students will be on a single "master" story. When this "master" story is updated, all students are moved to the new story, regardless of whether they have completed the old story's events. This creates continuity errors for a large number of students, which is undesirable.

The proposed solution is to have all stories uploaded to the cloud, but a master file will dictate the "latest" story that is accessible by students. Students will be able to play through all main story content up to the "latest" story. This master file should ideally automatically advance the pointer to the "latest" story over the course of the semester.

**Comment by athuyaoo** [comment]
Good Issue!

**Comment by wltan** [comment]
The system for the master file has been set up. It will be available as `master.xml` in the same directory as the rest of the stories. An example file can be found at: https://gist.github.com/wltan/8e82d42a8ac9e71a9d82e9019aa5cbaa

The syntax should be quite self-explanatory. Some notes:
- `key` is a unique integer to identify each story. As integers have a total ordering, we assume that the student will go through the stories in ascending order, and that the respective open/close dates will be consistent with it.
- The `<STORY>` tags in the master file have a different syntax from the mission files, as they have different functions, although symbolically they represent the same thing.
- Behavior is undefined if there are no open missions. The first and last missions ought to be adjusted accordingly if there is a problem.
